1.	Write a Python Program to Add Two Matrices?

In [8]:

import numpy as np
  
R = int(input("Enter the number of rows for first matrix:"))
C = int(input("Enter the number of columns for the first matrix:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries_first = list(map(int, input().split()))
  
# For printing the matrix
matrix = np.array(entries_first).reshape(R, C)
print(matrix)



  
R_1 = int(input("Enter the number of rows for second Matrix:"))
C_1 = int(input("Enter the number of columns for second Matrix:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries_second = list(map(int, input().split()))
  
# For printing the matrix
matrix_2 = np.array(entries_second).reshape(R_1, C_1)
print(matrix_2)
result=[[0,0],[0,0]]
for i in range(len(matrix)):
  for j in range(len(matrix[0])):
       result[i][j] = matrix[i][j] + matrix_2[i][j]
print(f"The sum of matrices is --  {result}")

Enter the number of rows for first matrix:2
Enter the number of columns for the first matrix:2
Enter the entries in a single line (separated by space): 
1 2 3 4
[[1 2]
 [3 4]]
Enter the number of rows for second Matrix:2
Enter the number of columns for second Matrix:2
Enter the entries in a single line (separated by space): 
3 2 0 5
[[3 2]
 [0 5]]
The sum of matrices is --  [[4, 4], [3, 9]]


2.	Write a Python Program to Multiply Two Matrices?

In [12]:
import numpy as np
R = int(input("Enter the number of rows for first matrix:"))
C = int(input("Enter the number of columns for the first matrix:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries_first = list(map(int, input().split()))
  
# For printing the matrix
matrix = np.array(entries_first).reshape(R, C)
print(matrix)



  
R_1 = int(input("Enter the number of rows for second Matrix:"))
C_1 = int(input("Enter the number of columns for second Matrix:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries_second = list(map(int, input().split()))
matrix_2 = np.array(entries_second).reshape(R_1, C_1)

if C!=R_1:
  print("Matrix multiplication is not possible")
else:
  matrix_mult=np.matmul(matrix,matrix_2)
print("matrix multiplication")
print(matrix_mult)

Enter the number of rows for first matrix:2
Enter the number of columns for the first matrix:2
Enter the entries in a single line (separated by space): 
1 1 1 1
[[1 1]
 [1 1]]
Enter the number of rows for second Matrix:2 
Enter the number of columns for second Matrix:2
Enter the entries in a single line (separated by space): 
3 3 3 3
matrix multiplication
[[6 6]
 [6 6]]


3.	Write a Python Program to Transpose a Matrix?

In [13]:
R = int(input("Enter the number of rows for first matrix:"))
C = int(input("Enter the number of columns for the first matrix:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries_first = list(map(int, input().split()))
  
# For printing the matrix
matrix = np.array(entries_first).reshape(R, C)
print(matrix)

transpose_matrix=np.transpose(matrix)

print(f"The transposed matrix is {transpose_matrix}")

Enter the number of rows for first matrix:2
Enter the number of columns for the first matrix:2
Enter the entries in a single line (separated by space): 
2 3 1 5
[[2 3]
 [1 5]]
The transposed matrix is [[2 1]
 [3 5]]


4.	Write a Python Program to Sort Words in Alphabetic Order?

In [18]:
input_sentence=input("enter the sentence you want to sort words")
output=""
words=input_sentence.split()
words.sort()
for i in words:
  print(i)


enter the sentence you want to sort wordsapple zebra cat bad
apple
bad
cat
zebra


5.	Write a Python Program to Remove Punctuation From a String?

In [21]:
import regex as re
str="hello %$@Friday%^&"
res = re.sub(r'[^\w\s]', '', str)
print(f"The punctated removed string is :-- {res}")

The punctated removed string is :-- hello Friday
